// <auto-generated />
namespace AIR_SVU_S19.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview3-19553-01")]
    public sealed partial class table_Files : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(table_Files));
        
        string IMigrationMetadata.Id
        {
            get { return "201911141809172_table_Files"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
